<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'app.security.login_form_authenticator' shared autowired service.

return $this->services['app.security.login_form_authenticator'] = new \AppBundle\Security\LoginFormAuthenticator();
