<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX62esik\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX62esik/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerX62esik.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerX62esik\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerX62esik\appProdProjectContainer([
    'container.build_hash' => 'X62esik',
    'container.build_id' => 'f160c069',
    'container.build_time' => 1573403045,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX62esik');
