<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7wgyrqx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7wgyrqx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container7wgyrqx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container7wgyrqx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container7wgyrqx\appDevDebugProjectContainer([
    'container.build_hash' => '7wgyrqx',
    'container.build_id' => '7d9f22ba',
    'container.build_time' => 1573426006,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7wgyrqx');
