<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXevgh5g\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXevgh5g/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXevgh5g.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXevgh5g\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXevgh5g\appDevDebugProjectContainer([
    'container.build_hash' => 'Xevgh5g',
    'container.build_id' => '449d36a3',
    'container.build_time' => 1573492472,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXevgh5g');
