<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\DataFixtures\ORM\LoadFixtures' shared service.

return $this->services['AppBundle\\DataFixtures\\ORM\\LoadFixtures'] = new \AppBundle\DataFixtures\ORM\LoadFixtures();
